name: Test Release

on:
  workflow_dispatch:
    branches:
      - master

env:
  DEFAULT_PYTHON: "3.10"

jobs:
  pypi:
    name: Upload to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3

      - name: Setup Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@master
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build dist
        run: python -m build

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
          verbose: true
